version: "3.9"

services:
  web:
    container_name: fyp-recsys-web
    image: nbean452/fyp-recsys-web

  api:
    container_name: fyp-recsys-api
    image: nbean452/fyp-recsys-api
    env_file:
      - ./.env
    volumes:
      - $PWD/server_data:/code/server_data:Z
