version: "3.9"

services:
  web:
    container_name: fyp-recsys-api
    image: fyp-recsys-api
    build: .
    env_file:
      - ./.env

  api:
    container_name: fyp-recsys-web
    image: fyp-recsys-web
    build: ../fyp-recsys-web/
    env_file:
      - ./.env

  caddy:
    image: caddy/caddy:2.6.2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/serv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
