version: "3.9"

services:
  web:
    container_name: fyp-recsys-web
    image: nbean452/fyp-recsys-web
    networks:
      - shared_network

  api:
    container_name: fyp-recsys-api
    image: nbean452/fyp-recsys-api
    networks:
      - shared_network
    env_file:
      - ./.env
    volumes:
      - $PWD/server_data:/code/server_data:Z

networks:
  default:
    name: shared_network
    external: true