version: "3.9"

services:
  django:
    container_name: fyp-recsys-api
    image: nbean452/fyp-recsys-api
    build: .
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  nextjs:
    container_name: fyp-recsys-web
    image: "nbean452/fyp-recsys-web"
    build: ../fyp-recsys-web/
    environment:
      - NEXT_PUBLIC_PROD_URL=https://capstone-api.nbenedictcodes.com
      - NEXT_PUBLIC_DEV_URL=http://localhost:9000

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy_service
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/serv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
