version: "3.9"

services:
  web:
    container_name: fyp-recsys-web
    platform: linux/amd64
    image: nbean452/fyp-recsys-web
    build: ../fyp-recsys-web/

  api:
    container_name: fyp-recsys-api
    platform: linux/amd64
    image: nbean452/fyp-recsys-api
    build: .
#    env file
#    env_file:
#      - ./.env
#    volumes for storing data
#    volumes:
#      - $PWD/server_data:/code/server_data:Z
